### ISSUE TITLE
rating filters are not dynamic

### ISSUE THREAD

**Issue by fossfreedom** [donaghhorgan/rhythmbox-plugins-rating-filters#2]
A couple of observations.

If I change a rating for a track to equal or more the value in preference, clicking between All Rating and favourites never updates the filtered list UNTIL the preferences is changed.

Second observation - if I'm on the favourites filter and change the preferences value, I think the filter should be dynamically updated on screen rather than the user having to toggle between All Ratings and Favourites.

**Comment by donaghhorgan** [comment]
Good suggestions, thanks! Any idea how to connect a callback to the rating changed signal? I had a quick look at the bindings, but I can't make out how RB.Rating::rated is related to the shell.

http://www.jetmore.org/john/misc/rb/rb297-python-bindings/RB.Rating-rated.html

**Comment by fossfreedom** [comment]
yep - have a look at the code here
- https://github.com/fossfreedom/coverart-browser/blob/release-0.7/coverart_album.py

Specifically the class `class AlbumLoader(GObject.Object):`

You need to connect to the 3 signals as shown in the connect_signals method

Then in the`_entry_changed_callback` you can see what is changed - I presume you are looking for the 

`RhythmDBPropType.RATING`
- http://www.jetmore.org/john/misc/rb/rb297-python-bindings/RB.RhythmDBPropType.html

**Comment by donaghhorgan** [comment]
Great, thanks. I won't have a chance to fix it this week, but I'll try to get around to it some time next week.

**Comment by fossfreedom** [comment]
hey - no worries :)

... and if you are feeling the need for  challenge, we've got lots of issues to wade through on our coverart browser - we need talented developers like your goodself.

**Comment by donaghhorgan** [comment]
I'd love to help, but I'm trying to finish off my PhD before May so my
schedule is a bit hectic. I should have more free time after then though,
so maybe this summer!

**Comment by donaghhorgan** [comment]
I just pushed a change that should fix your second observation above. Thanks again for the help!

I'll try to get around to the preference callback later in the week!

**Comment by donaghhorgan** [comment]
I just pushed an update that implements the preference change callback. Would you mind trying it out and letting me know if it's up to spec? I meant to get around to fixing it sooner, but I've been away in thesis land for the last three weeks...

**Comment by fossfreedom** [comment]
hey - no worries!

Looks good - cant see any issues with the fixes. 

cheers!

**Comment by donaghhorgan** [comment]
Great, thanks!
